// Generated by CoffeeScript 1.6.2
(function() {
  var Cli, optimist;

  optimist = require('optimist');

  module.exports = Cli = (function() {
    function Cli(version) {
      this.version = version;
      this.usage = ("" + 'Snapshooter' + " ") + ("v" + this.version + "\n").grey;
      this.usage += "Simple crawler for Single Page Applications\n\n".grey;
      this.usage += "" + 'Usage:' + "\n";
      this.usage += "  snapshooter [" + 'options'.green + "] [" + 'params'.green + "]";
      this.examples = "\n\nExamples:\n  snapshooter -a <site.com> -o <local-folder>\n  snapshooter -a <site.com> -o <local-folder> -p\n  snapshooter -a <site.com> -o <local-folder> -ps [--port 3000]\n\n  snapshooter -f <local-file.html> -o <local-folder>\n  snapshooter -f <site.com> -o <local-folder> -p\n  snapshooter -f <site.com> -o <local-folder> -ps [--port 3000]\n";
      this.argv = (this.opts = optimist.usage(this.usage).alias('a', 'address').describe('a', 'Http address to crawl').alias('f', 'file').describe('f', 'Local file to crawl').alias('o', 'output').describe('o', 'Output folder to save crawled static files').alias('p', 'pretty').describe('p', 'Output crawled html files in a pretty fashion way').alias('s', 'server').describe('s', 'Start a server for previewing crawled content').describe('port', 'Preview server port')["default"]('port', 8080).describe('once', 'Avoid recursivity, loading only the first given url').describe('stdout', 'Prints crawled content instead of writing file').alias('v', 'version').describe('v', 'Shows snapshooter version').alias('h', 'help').describe('h', 'Shows this help screen')).argv;
    }

    return Cli;

  })();

}).call(this);

/*
//@ sourceMappingURL=cli.map
*/
