// Generated by CoffeeScript 1.6.2
(function() {
  var Cli, Shoot, Snapshooter, colors, fs, fsu, path;

  require('source-map-support').install();

  fs = require('fs');

  path = require('path');

  colors = require('colors');

  fsu = require('fs-util');

  Shoot = require('./core/shoot');

  Cli = require('./cli');

  module.exports = Snapshooter = (function() {
    function Snapshooter() {
      var _this = this;

      this.version = (require('./../package.json')).version;
      this.cli = new Cli(this.version);
      if (this.cli.argv.input) {
        if (fs.existsSync(this.cli.argv.output)) {
          return this.prompt('Output folder exists, overwite?', /.*/, 'y', function(answer) {
            if (answer.toLowerCase() === 'y') {
              fsu.rm_rf(_this.cli.argv.output);
              return _this.init();
            } else {
              console.log('Aborting..');
              return process.exit();
            }
          });
        } else {
          console.log('• ERROR '.bold + 'Output dir not informed!'.red);
        }
      }
      console.log(this.cli.opts.help() + this.cli.examples);
    }

    Snapshooter.prototype.init = function() {
      return new Shoot(this, this.cli);
    };

    Snapshooter.prototype.prompt = function(question, format, _default, fn) {
      var stdin, stdout,
        _this = this;

      stdin = process.stdin;
      stdout = process.stdout;
      if (_default != null) {
        question += " [" + _default + "]";
      }
      stdout.write("" + question + ": ");
      return stdin.once('data', function(data) {
        var msg, rule;

        data = data.toString().trim() || _default;
        if (format.test(data)) {
          return fn(data.trim());
        } else {
          msg = "" + 'Invalid entry, it should match:'.red;
          rule = "" + (format.toString().cyan);
          stdout.write("\t" + msg + " " + rule + "\n");
          return _this.prompt(question, format, fn);
        }
      }).resume();
    };

    return Snapshooter;

  })();

}).call(this);

/*
//@ sourceMappingURL=snapshooter.map
*/
