// Generated by CoffeeScript 1.6.2
(function() {
  var Cli, Shoot, Snapshooter, colors, fs, path;

  require('source-map-support').install();

  fs = require('fs');

  path = require('path');

  colors = require('colors');

  Shoot = require('./core/shoot');

  Cli = require('./cli');

  module.exports = Snapshooter = (function() {
    function Snapshooter() {
      this.version = (require('./../package.json')).version;
      this.cli = new Cli(this.version);
      if (this.cli.argv.input) {
        return new Shoot(this, this.cli);
      }
      console.log(this.cli.opts.help() + this.cli.examples);
    }

    return Snapshooter;

  })();

}).call(this);

/*
//@ sourceMappingURL=snapshooter.map
*/
