// Generated by CoffeeScript 1.6.2
(function() {
  var Crawler, pd, phantom,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  phantom = require('phantom');

  pd = (require('pretty-data')).pd;

  /*
    Create and instantiate phantomjs thought phantom
  */


  module.exports = Crawler = (function() {
    var port;

    Crawler.prototype.ph = null;

    Crawler.prototype.page = null;

    Crawler.prototype.start_time = null;

    port = 12345;

    function Crawler(cli, url, done) {
      var _this = this;

      this.cli = cli;
      this.url = url;
      this.done = done;
      this.keep_on_checking = __bind(this.keep_on_checking, this);
      this.start_time = (new Date).getTime();
      phantom.create('--load-images=false', function(ph, err1) {
        var msg;

        _this.ph = ph;
        if (err1 != null) {
          msg = '• ERROR '.bold.red + 'phantom.create couldn\'t finish for '.red;
          msg += _this.url.yellow;
          return _this.error(msg, err1);
        }
        return _this.ph.createPage(function(page, err2) {
          _this.page = page;
          if (err2 != null) {
            msg = '• ERROR '.bold.red + 'ph.create couldn\'t finish for '.red;
            msg += _this.url.yellow;
            return _this.error(msg, err2);
          }
          return _this.page.open(_this.url, function(status, err3) {
            if (err3 != null) {
              msg = '• ERROR '.bold.red + 'page.open couldn\'t finish for '.red;
              msg += _this.url.yellow;
              return _this.error(msg, err3);
            }
            if (status !== 'success') {
              msg = '• ERROR '.bold.red + ' ' + _this.url.yellow;
              msg += " ended with status = ".red + status.bold;
              return _this.error(msg);
            }
            return _this.keep_on_checking();
          });
        });
      }, 'phantomjs', port++);
    }

    Crawler.prototype.keep_on_checking = function() {
      var _this = this;

      return this.page.evaluate(function() {
        var data;

        return data = {
          rendered: window.crawler && window.crawler.is_rendered,
          source: document.all[0].outerHTML
        };
      }, function(data) {
        var msg;

        if (!(data != null ? data.rendered : void 0)) {
          if (((new Date).getTime()) - _this.start_time > (_this.cli.argv.timeout * 1000)) {
            msg = '• ERROR '.bold.red + _this.url.yellow;
            msg += ' took too long to render, skipping'.red;
            return _this.error(msg);
          } else {
            return setTimeout(_this.keep_on_checking, 100);
          }
        }
        _this.ph.exit();
        if (_this.cli.argv.pretty) {
          return _this.done(pd.xml(data.source));
        } else {
          return _this.done(data.source);
        }
      });
    };

    Crawler.prototype.error = function(msg, error) {
      console.error(msg);
      if (error != null) {
        console.error(error);
      }
      this.ph.exit();
      return this.done(null);
    };

    return Crawler;

  })();

}).call(this);

/*
//@ sourceMappingURL=crawler.map
*/
