// Generated by CoffeeScript 1.6.3
(function() {
  var Crawler, Live, http;

  http = require('http');

  Crawler = require('./crawler');

  /*
    Http proxy for crawling live
  */


  module.exports = Live = (function() {
    function Live(the, cli) {
      var server,
        _this = this;
      this.the = the;
      this.cli = cli;
      server = http.createServer(function(req, res) {
        res.writeHead(200, {
          'Content-Type': 'text/html'
        });
        if (/\./.test(req.url)) {
          return res.end();
        }
        console.warn('trying to catch', _this.cli.argv.input + req.url);
        return new Crawler(_this.cli, _this.cli.argv.input + req.url, function(source) {
          return res.end(source);
        });
      });
      server.listen(this.cli.argv.port);
    }

    return Live;

  })();

}).call(this);

/*
//@ sourceMappingURL=live.map
*/
