// Generated by CoffeeScript 1.6.2
(function() {
  var Crawler, Shoot, connect, exec, fs, fsu, path;

  fs = require('fs');

  exec = (require('child_process')).exec;

  path = require('path');

  fsu = require('fs-util');

  connect = require('connect');

  Crawler = require('./crawler');

  /*
    Instantiate a crawler for the first url,
    Crawler returns a source and "<a href=''>" links url
  
    The links url are filtered ( i.e. external links are not crawled ),
    and then written to disk
  */


  module.exports = Shoot = (function() {
    Shoot.prototype.crawled = {};

    Shoot.prototype.root_url = null;

    Shoot.prototype.pending_urls = null;

    Shoot.prototype.connections = 0;

    Shoot.prototype.max_connections = 10;

    function Shoot(the, cli) {
      var code, msg;

      this.the = the;
      this.cli = cli;
      if (!this.has_phantom()) {
        msg = "" + 'Error'.bold.red + " Install " + 'phantomjs'.yellow + " before indexing pages!\n  • http://phantomjs.org";
        console.log(msg);
        process.exit(code = process.ENOENT);
      }
      this.pending_urls = [];
      if (this.cli.argv.address) {
        if (!~this.cli.argv.address.indexOf('http')) {
          this.cli.argv.address = 'http://' + this.cli.argv.address;
        }
      }
      this.root_url = this.cli.argv.address || this.cli.argv.file;
      this.crawl(this.root_url);
    }

    Shoot.prototype.crawl = function(url) {
      var _this = this;

      if (this.crawled[url] === true) {
        return;
      }
      this.crawled[url] = false;
      console.log('>'.bold.yellow, url.grey);
      this.connections++;
      return new Crawler(this.cli, url, function(source) {
        console.log('< '.bold.cyan, url.grey);
        _this.connections--;
        _this.crawled[url] = true;
        _this.save_page(url, source);
        return _this.after_crawl(source);
      });
    };

    Shoot.prototype.after_crawl = function(source) {
      var absolute, links, match, reg, relative;

      reg = /a href="(.+)"/g;
      links = [];
      if (source != null) {
        while ((match = reg.exec(source)) != null) {
          relative = match[1];
          absolute = this.root_url + relative;
          if (relative !== '/' && (this.crawled[absolute] == null)) {
            this.pending_urls.push(absolute);
          }
        }
      }
      while (this.connections < this.max_connections && this.pending_urls.length) {
        this.crawl(this.pending_urls.shift());
      }
      if (this.connections === 0) {
        return this.finish();
      }
    };

    Shoot.prototype.save_page = function(url, source) {
      var output_file, output_folder, relative_url;

      relative_url = (url.replace(this.root_url, '')) || '/';
      output_folder = path.join(this.cli.argv.output, relative_url);
      output_file = path.join(output_folder, 'index.html');
      if (!fs.existsSync(output_folder)) {
        fsu.mkdir_p(output_folder);
      }
      fs.writeFileSync(output_file, source);
      return console.log('✓ '.green, relative_url);
    };

    Shoot.prototype.finish = function() {
      var address;

      console.log('\n★  Application crawled successfully!'.green);
      if (!this.cli.argv.server) {
        return;
      }
      this.conn = connect().use(connect["static"](this.cli.argv.output)).listen(this.cli.argv.port);
      address = 'http://localhost:' + this.cli.argv.port;
      return console.log('\nPreview server started at: \n\t'.grey, address);
    };

    Shoot.prototype.has_phantom = function() {
      var _this = this;

      return exec("phantomjs -v", function(error, stdout, stderr) {
        return /phantomjs: command not found/.test(stderr);
      });
    };

    return Shoot;

  })();

}).call(this);

/*
//@ sourceMappingURL=shoot.map
*/
